-- MySQL Script generated by MySQL Workbench
-- Wed Mar 24 21:07:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema formationEAD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema formationEAD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS formationEAD DEFAULT CHARACTER SET utf8 ;
USE formationEAD ;
-- -----------------------------------------------------
-- Table formationEAD.tb_pessoa
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS formationEAD.students (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  desname VARCHAR(45) NOT NULL,
  desdoc VARCHAR(14) NOT NULL,
  desformation VARCHAR(45) NOT NULL,
  desregister VARCHAR(20) NOT NULL, 
  updated_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS formationEAD.administrators(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  deslogin VARCHAR(20),
  despassword VARCHAR(255),
  updated_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into administrators(deslogin, despassword, updated_at, created_at) values('formacao.ead', '$2y$10$z.Mh2t4nI.nCjVhxuSFpf.IlL5B8J7bBPQK8iLyDCc84K7evmjqyG', '2021-04-01 12:41:04', '2021-04-01 12:41:04');


